### ISSUE TITLE
Would like to see border color parameterized. 

### ISSUE THREAD

**Issue by DandrewsDev** [caglarylmz/slide_digital_clock#11]
Currently if I display the clock on anything without a white background there is a border around each section of the clock.

<img width="241" alt="Screen Shot 2022-12-12 at 16 36 28" src="https://user-images.githubusercontent.com/3299799/207159802-3934e49c-e272-42ce-a5b7-ee7f6a0574fd.png">

There are 3 cases of
`border: Border.all(color: Colors.white),`
One each for hours, minutes, seconds.
 
I would love to be able to control this boarder color to either set it as transparent, or a custom color for each section.

**Comment by caglarylmz** [comment]
thx for advice. Now u can use.
