### ISSUE TITLE
where is the hourMinuteDigitDecoration?

### ISSUE THREAD

**Issue by paulobreim** [caglarylmz/slide_digital_clock#12]
I was using

        appBar: AppBar(
          centerTitle: true,
          title: Image.asset(
            'assets/images/logotitle.png',
            fit: BoxFit.cover,
          ),
          toolbarHeight: 77,
          backgroundColor: Colors.black,
          foregroundColor: Colors.yellow,
          systemOverlayStyle:
              const SystemUiOverlayStyle(statusBarColor: Colors.blue),
          actions: <Widget>[
            DigitalClock(
              areaDecoration: const BoxDecoration(color: Colors.transparent),
              areaAligment: AlignmentDirectional.center,
              hourMinuteDigitDecoration:
                  const BoxDecoration(color: Colors.transparent),
              hourMinuteDigitTextStyle: const TextStyle(fontSize: 15),
              secondDigitTextStyle: const TextStyle(fontSize: 11),
            )
          ],
        ),

But in the last version,  **hourMinuteDigitDecoration**  does not exist and in changelog  there are no information about it.
vscode suggested to switch to minuteDigitDecoration and I switched, but the result changed completely.

Antes eu tinha:
![Screenshot_20230306_125740](https://user-images.githubusercontent.com/381594/223163172-eed26e20-1cf2-4b87-bc85-52eaf986a797.png)

e agora

![Screenshot_20230306_125825](https://user-images.githubusercontent.com/381594/223163340-617a8ed0-6354-4272-bdba-969a5e8d0f9b.png)

For now I will stop using this lib because it is unreasonable to make changes without proper documentation since the impact on productivity is very significant.

tks.

**Comment by caglarylmz** [comment]
yes you are right, i should have mentioned the change. but the change is understandable if you look at the example I have presented. In the old version, hours and minutes could not be parsed. Now a different design can be made for each digit.
hourMinuteDigitDecoration ->hourDigitDecoration, minuteDigitDecoration and secondDigitDecoration
all decoraiton seperate. thank you for your warning

**Comment by paulobreim** [comment]
Thank you for your answer.
