### ISSUE TITLE
Null safety in flutter sdk '>=2.12.0 <3.0.0'

### ISSUE THREAD

**Issue by ParasRai2** [caglarylmz/slide_digital_clock#6]
Xcode's output:
↳
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:
- package:slide_digital_clock

**Comment by LiveRock** [comment]
Any plans to make it null safety?

**Comment by jigarfumakiya** [comment]
Hey, @LiveRock  I have created PR for null safety #7.

**Comment by caglarylmz** [comment]
Thx for advice
